#!/usr/bin/env bash
set -euo pipefail

# push.sh - commit and push current changes
# Usage:
#   ./push.sh                => commit with autogenerated update timestamp message and push
#   ./push.sh update         => commit with autogenerated update timestamp message and push
#   ./push.sh "my message"   => commit with provided message and push

# move to repo root if inside a git worktree
repo_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$repo_root" ]; then
  echo "Error: this script must be run inside a git repository."
  exit 1
fi
cd "$repo_root"

cmd="${1:-update}"
if [ "$#" -gt 0 ]; then
  shift || true
fi

if [ "$cmd" = "update" ]; then
  msg="update: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
else
  # allow multi-word messages
  msg="$cmd"
  if [ "$#" -gt 0 ]; then
    msg="$msg $*"
  fi
fi

echo "Staging changes..."
git add -A

if git diff --cached --quiet; then
  echo "No staged changes to commit. Will still attempt to push current branch."
else
  echo "Committing: $msg"
  git commit -m "$msg"
fi

upstream_ref="$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null || true)"

if [ -n "$upstream_ref" ]; then
  remote="${upstream_ref%%/*}"
  branch="${upstream_ref#*/}"
else
  remote="origin"
  branch="$(git branch --show-current)"
  if [ -z "$branch" ]; then
    branch="main"
  fi
fi

echo "Pushing to ${remote}/${branch}..."
git push "$remote" HEAD:"$branch"

echo "Done. Pushed to ${remote}/${branch}."